### ISSUE TITLE
add a console clear function

### ISSUE THREAD

**Issue by lorezzed** [purescript/purescript-console#11]
In the Getting Started[0] guide is a solution to a Project Euler question. I continued working through questions using the Try Purescript REPL[1] and noticed I couldn't clear out my console easily. It would be nice to go `console.clear()` at the top of my solutions :)

Clear is missing in
https://pursuit.purescript.org/packages/purescript-console/2.0.0/docs/Control.Monad.Eff.Console

As described here
https://developer.mozilla.org/en-US/docs/Web/API/Console/clear

[0] http://www.purescript.org/learn/getting-started/
[1] http://try.purescript.org

**Comment by paf31** [comment]
👍 Seems like a good idea.

**Comment by matthewleon** [comment]
PR here: https://github.com/purescript/purescript-console/pull/13

**Comment by matthewleon** [comment]
Okay, this is now available here: https://pursuit.purescript.org/packages/purescript-console-browser-specific/0.0.1
