### ISSUE TITLE
Logging an `Error`

### ISSUE THREAD

**Issue by natefaubion** [purescript/purescript-console#12]
Logging an `Error` has the effect of logging the original stack trace, just as if the exception was caught by the runtime. Using `error` with a string, or via `show`, erases the trace. Can we provide a function `error' :: forall eff. Error -> Eff (console :: CONSOLE | eff) Unit`?

**Comment by paf31** [comment]
Sounds good

**Comment by paf31** [comment]
But `Error` is defined in `exceptions`, so maybe there? I'm wondering about alternative backends here.

**Comment by natefaubion** [comment]
I'm fine with that as well. `exceptions` would end up depending on `console`, in that case.

**Comment by garyb** [comment]
I guess this can be resolved without the dependency, now these have moved to `Effect`.
