### ISSUE TITLE
debug/debugShow is missing

### ISSUE THREAD

**Issue by andys8** [purescript/purescript-console#31]
`console.{log,warn,error}` are implemented with bindings.
`console.debug` is missing.

Is there a reason? Can it be added / would a PR be welcome?

https://developer.mozilla.org/de/docs/Web/API/Console/debug

**Comment by JordanMartinez** [comment]
It was possibly overlooked? MDN says that it's been compatible with browsers for quite some time. 

This works in a Node environment, too, correct?

**Comment by andys8** [comment]
For node available since version 8. Docs say it's just an alias. Browsers show different highlighting, allow filtering and hide this level by default.

https://nodejs.org/api/console.html#console_console_debug_data_args

**Comment by JordanMartinez** [comment]
Actually, should this be added here because this is a core library? Would other backends be able to implement this, too? I'm not sure.

**Comment by garyb** [comment]
I don't see why not, it could just print to stdout if nothing more suitable is available!

**Comment by JordanMartinez** [comment]
Ah, good point.
