### ISSUE TITLE
Version of log function that works on all types

### ISSUE THREAD

**Issue by flip111** [purescript/purescript-console#38]
`log :: a -> Effect Unit`

Would be nice to have this function so we can just dump anything in there as we could with JavaScript. https://developer.mozilla.org/en-US/docs/Web/API/Console/log

I don't think `logShow` is a valid substitute as i think (but did not verify) that the developer console does different formatting when it operates on a different type.

Especially useful in combination with `Foreign` to avoid casting and type checks.

**Comment by garyb** [comment]
That's what `purescript-debug` is for 🙂: https://pursuit.purescript.org/packages/purescript-debug/docs/Debug

This library is for more principled writing to the console, for CLI apps, for instance.
