### ISSUE TITLE
Are logAny and errorAny actually unsafe?

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript-console#6]
Maybe they should be in `Control.Monad.Eff.Console`? See also purescript/purescript#1675

**Comment by zudov** [comment]
I am not sure

There is a discussion here http://ircbrowse.net/browse/purescript?id=155631&timestamp=1440002592#t1440002592 (spans for around 3 pages)

And in PR https://github.com/purescript/purescript-console/pull/4

**Comment by hdgarrood** [comment]
I guess this depends on your philosophy, and I'm not going to spend much time worrying about this, but given that it only becomes unsafe when combined it with other effects (ie, you need to read the process' own stdout somehow) I'm not quite convinced. Any instance of a program observing itself from "outside" is liable to break all kinds of guarantees, I think.

**Comment by zudov** [comment]
I am also pretty much neutral on that question
