### ISSUE TITLE
Bower package needs updating

### ISSUE THREAD

**Issue by doivosevic** [purescript/purescript-console#9]
I'm getting 50 compile warnings from purescript-console and I see that the bower package is behind this repo. Could someone update?

**Comment by doivosevic** [comment]
I apologise. It's mostly from purescript-prelude

**Comment by garyb** [comment]
Bower doesn't need updating itself, when you choose to `bower install` something it looks at the tags on the repo, and chooses the latest stable version. You have to specifically ask for the release candidate versions by specifying the version, e.g. `bower i purescript-console#^1.0.0-rc.1`.
